comment/urls.py
from django.urls import path
from .views import *

app_name = 'comment'

urlpatterns = [
    path('detail/<int:id>', detail_post, name='detail_post'),
    path("comment/<int:id>", comment_post,name='comment_post'),
    path("comment/del/<int:id>", del_com,name='del_com'),
    path("comment/del1/<int:id>", del1_com,name='del1_com')
]

ecwa/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jurnal/', include('jurnal.urls')),
    path('accounts/', include('accounts.urls')),
    path('comment/', include('comment.urls')),
    path('forum/', include('forum.urls')),
    path('faq/', include('faq.urls')),
    path('error/', include('error.urls')),
]

faq/urls.py
from django.urls import path

from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.home, name='home'),
    path('update2/', views.update_faq_2, name='update_faq_2'),
    path('update/', views.update_faq, name='update_faq'),
    path('create/', views.create_faq, name='create_faq'),
    path('delete/', views.delete_faq, name='delete_faq'),
]

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.allthread, name='allthread'),
    path('newthread', views.newthread, name='newthread'),
    path("like/<int:id>",views.like_post,name='like_post'),
    path("delete/<int:id>", views.delete_post, name='delete_post'),
    path("update", views.update_post, name="update_post"),
]

comment/models.py
from django.db import models
from django.contrib.auth.models import User
from forum.models import Post, Like
# Create your models here.

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(max_length=100)
    deleted = models.BooleanField(default=False)

comment/forms.py
from django import forms
from .models import *

class FormPost(forms.ModelForm):
    title = forms.CharField(max_length=50, widget=forms.TextInput(attrs = {"placeholder" : "Title, max 50 characters", 'class': 'form-control my-1'}), label = "")
    content = forms.CharField(max_length=1500, widget=forms.Textarea(attrs = {"placeholder" : "Content, max 1500 characters", 'class': 'form-control my-1', 'rows':'3'}), label = "")
    class Meta:
        model = Post
        exclude = ["user"]

class FormComment(forms.ModelForm):
    content = forms.CharField(max_length=500, widget=forms.Textarea(attrs = {"placeholder" : "Insert Comment Here, max 500 characters", 'class': 'form-control', 'rows':'3'}), label = "")
    class Meta:
        model = Comment
        exclude = ["user","post", "deleted"]

comment/views.py
from django.shortcuts import render, redirect, reverse
from .forms import FormPost, FormComment
from .models import *

def add_post(request):
    if not request.user.is_authenticated:
        return "kontol"
    if request.method == "POST":
        post_form = FormPost(request.POST)
        if post_form.is_valid():
            post_form.instance.user = request.user
            post_object = post_form.save()
        return redirect(reverse("comment:detail_post", args=[post_object.id]))

    context = {
        "post_form" : FormPost,
        "is_add_post" : True,
    }
    return render(request,"comment/add_post.html",context)


def detail_post(request, id):
    thepost = Post.objects.get(id=id)
    likes = len(Like.objects.filter(post = thepost))
    comments = Comment.objects.filter(post = thepost)
    context = {
        "post" : thepost,
        "like" : likes,
        "commentlist" : comments,
        "comment_form": FormComment,
        "comment_count": len(comments)
    }
    return render(request, "comment/detail.html", context)

def like_post(request, id):
    if not request.user.is_authenticated:
        return "kontol"
    try:
        like = Like.objects.get(user = request.user, post = Post.objects.get(id=id))
    except:
        like = Like.objects.create(user=request.user, post = Post.objects.get(id=id))
        return redirect(reverse("comment:detail_post", args=[like.post.id]))
    return redirect(reverse("comment:detail_post", args=[id]))

def home(request):
    listofposts = Post.objects.all()
    listofpostandlikes = []
    for posts in listofposts:
        listofpostandlikes.append((posts, len(Like.objects.filter(post = posts))))
    context = {
        "postlist" : listofpostandlikes,
    }
    return render(request, 'comment/listpost.html', context)

def del_com(request, id):
    thecomment = Comment.objects.get(id=id)
    if thecomment.user == request.user:
        thecomment.content = "[deleted]"
        thecomment.deleted = True
        thecomment.save(update_fields=['content', 'deleted'])
    return redirect(reverse("comment:detail_post", args=[thecomment.post.id]))

def del1_com(request, id):
    thecomment = Comment.objects.get(id=id)
    currentpostid = thecomment.post.id
    if request.user.is_superuser:
        thecomment.delete()
    return redirect(reverse("comment:detail_post", args=[currentpostid]))

def comment_post(request, id):
    if not request.user.is_authenticated:
        return "kontol"
    if request.method == "POST":
        comment_form = FormComment(request.POST)
        if comment_form.is_valid():
            comment_form.instance.user = request.user
            comment_form.instance.post = Post.objects.get(id=id)
            comment_form.save()
    return redirect(reverse("comment:detail_post", args=[Post.objects.get(id=id).id]))

comment/templates/comment/add_post.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Quarantine Stories</title>
{% endblock meta %}

{% block content %}
<p class="h3 text-light">New Post</p>
<div class="mb-3 p-1 bg-light shadow rounded border" style="min-height:3rem;">
<form action="{% url 'comment:add_post' %}" method="POST" class="d-flex justify-content-center align-items-center flex-column mt-2">
    {% csrf_token %}
    {{post_form}}
    <input class="btn btn-success mt-2" type="submit" value="Submit Post">
</form>
</div>
{% endblock content %}

comment/templates/comment/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Ganteng</title>
{% endblock meta %}

{% block content %}
<div class="d-flex flex-column mx-5 mt-3">
<div class="mt-3 p-1 bg-light shadow rounded border" style="min-height:3rem;">
    <div class="d-flex flex-row justify-content-between">
        <p class="text-dark mb-1 h5"><strong>{{post.title}}</strong></p>
        <div class="d-flex flex-row">
            <a type="button" href="{% url 'forum:delete_post' post.id%}" class="btn btn-primary btn-sm">Delete</a>
            <p class="text-dark mb-1 h5"><strong>{{post.id}}</strong></p>
        </div>
    </div>
    <p class="text-dark mb-1"><strong>by {{post.user.name}}</strong></p>
    <p class="text-dark mb-1 border-top">{{post.content}}</p>
    <div class="d-flex flex-row justify-content-end border-top">
    <a href="{% url 'forum:like_post' post.id%}" class="text-dark p-1 mb-1">{{like}} 
    <img src="https://www.jing.fm/clipimg/full/5-51130_thumbs-clipart-achieved-thumbs-up-icon-copyright-free.png" alt="Tyme" style="max-width:1rem;position: relative;top: -2px;">
    </a>
    <p class="text-dark p-1 mb-1 ml-1">{{comment_count}}
    <img src="https://cdn.discordapp.com/attachments/916267375471525908/917330385107574784/comment-2551199-2136583.png" alt="Tyme" style="max-width:1.1rem;position: relative;top: -2px;">
    </p>
    </div>
</div>
<p class="mt-3 mb-3 ml-3 text-light h5"><strong><u>Comments</u></strong></p>
{% for comment in commentlist %}
    <div class="mb-3 p-1 bg-light shadow rounded border" style="min-height:3rem;">
        <p class="text-dark mb-1 border-bottom"><strong>by {{comment.user.username}}</strong></p>
        <p class="text-dark mb-1 border-bottom">{{comment.content}}</p>
        {% if comment.user == request.user and comment.deleted == False %}
        <a type="button" href="{% url 'comment:del_com' comment.id%}" class="btn btn-danger btn-sm">Delete Content</a>
        {% endif %}
        {% if request.user.is_superuser %}
        <a type="button" href="{% url 'comment:del1_com' comment.id%}" class="btn btn-danger btn-sm">Delete</a>
        {% endif %}
    </div>
{% endfor %}
<div class="mt-3 p-1 bg-light shadow rounded border" style="min-height:3rem;">
<form action="{% url 'comment:comment_post' post.id%}" method="POST" class="d-flex flex-column mt-2">
    {% if user.is_authenticated %}
    <p class="ml-2 border-bottom"><strong>by {{request.user.username}}</strong></p>
    {% else %}
    <p class="ml-2 border-bottom"><strong>Please register to comment</strong></p>
    {% endif %}
    {% csrf_token %}
    {{comment_form}}
    <input class="btn btn-success mt-2 font-weight-bold" type="submit" value="Submit Comment" style="min-width:4rem">
</form>
</div>
</div>
{% endblock content %}

comment/templates/comment/listpost.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Quarantine Stories</title>
{% endblock meta %}

{% block content %}
<div class="d-flex flex-column mx-5 mt-3">
      <div class="d-flex flex-row">
        <p class="my-auto ml-2 h5 text-dark"><strong><u>Posts</u></strong></p>
      </div>
      {% for item in postlist %}
      <div class="border shadow mt-3 p-1 rounded bg-light">
        <p class="text-dark mb-1"><strong>{{item.0.user.username}}</strong></p>
        <a class="text-dark mb-1 h5" href="{% url 'comment:detail_post' item.0.id %}"><strong>{{item.0.title}}</strong></a>
        <div class="border-top d-flex justify-content-end"><p class="text-dark mb-1 mt-1">{{item.1}} <img src="https://www.jing.fm/clipimg/full/5-51130_thumbs-clipart-achieved-thumbs-up-icon-copyright-free.png" alt="Tyme" style="max-width:1rem;position: relative;top: -2px;"></p></div>
      </div>
      {% endfor %}
    </div>
{% endblock content %}