ecwa/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jurnal/', include('jurnal.urls')),
    path('accounts/', include('accounts.urls')),
    path('comment/', include('comment.urls')),
    path('forum/', include('forum.urls')),
    path('faq/', include('faq.urls')),
    path('error/', include('error.urls')),
]

faq/urls.py
from django.urls import path

from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.home, name='home'),
    path('update2/', views.update_faq_2, name='update_faq_2'),
    path('update/', views.update_faq, name='update_faq'),
    path('create/', views.create_faq, name='create_faq'),
    path('delete/', views.delete_faq, name='delete_faq'),
]

faq/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    pesan = models.TextField()
    def __str__(self):
        return self.pesan

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)
    address = models.TextField(max_length=300, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=1, blank=True)
    phone_number = models.CharField(max_length=12, blank=True)
    occupation = models.CharField(max_length=100, blank=True)
    role = models.CharField(max_length=10, blank=True)
    description = models.TextField(max_length=500, blank=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

faq/forms.py
from django import forms

class Question(forms.Form):
    fields = ["pertanyaan"]
    error_messages = { "required": "masih kosong"}
    format_pesan = {"placeholder":"Masukkan pertanyaan dari Anda", "class" : "align-items-center justify-content-center form-control"}
    pertanyaan = forms.CharField(required = True, widget=forms.Textarea(attrs=format_pesan))

faq/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import forms
from .models import Question

# Create your views here.

def home(request):
    context= {
        'question_list':Question.objects.all()
    }
    print(context)
    return render(request, 'faq/home.html', context)

def create_faq(request):
    form = forms.Question()
    context = {'form':form}
    if request.method == "POST":
        print(request)
        form = forms.Question(request.POST)
        if form.is_valid():
            question = Question(pesan=form.cleaned_data['pertanyaan'])
            question.save()
            return redirect(reverse("faq:home"))
    return render(request, 'faq/create-faq.html', context)

def update_faq(request):
    context = {
        "id_question" : request.POST["id_question"]
    }
    if request.method == "POST":
        print(request.POST)
    return render(request, 'faq/update-faq.html', context)

def update_faq_2(request):
    """Update FAQ happens here"""
    context = {}
    if request.method == "POST":
        id = request.POST["id_question"]
        question = request.POST["question"]
        obj_q = Question.objects.get(id=id)
        obj_q.pesan = question
        obj_q.save()
    return redirect(reverse("faq:home"))

def delete_faq(request):
    id = request.GET['id']
    item = Question.objects.get(id=id)
    print(item)
    item.delete()
    return redirect(reverse("faq:home"))

faq/templates/faq/create-faq.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1 class="text-center">Form Mengajukan Pertanyaan</h1>
<div class="container">
    <div class="justify-content-center align-items-center mt-5">
        <!-- -->
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <button action="{% url 'faq:create_faq' %}" id="create-btn" class="btn text-light btn-primary p-1" type="submit">Submit</button>
        </form>
        <button id="btn-cancel" class="btn text-light btn-danger p-1 mt-3" type="submit">Batal</button>
    </div>
</div>

<script>
    $(document).ready(function() {
        $("#create-btn").click(function(event) {
            var question = $('#id_pertanyaan').val()
            if(question) {

            } else {
                event.preventDefault()
                alert("Silakan isi pertanyaan dahulu")
            }
        })
        $("#btn-cancel").click(function() {
            $.ajax({
                url: "{% url 'faq:home' %}",
                type: "GET",
                success: function(response){
                    window.location.href = "/faq/";
                }
            })
        })
    })
</script>
{% endblock content %}

faq/templates/faq/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1 class='text-center mt-5'>Welcome to FAQ!</h1>
<section class="d-flex justify-content-center align-items-center text-dark flex-column">
    {% for question in question_list %}
    <div class="card mt-3 mx-auto border-3 border-dark container-fluid w-75">
        <div class="card-body">
        <h5 class="card-title">{{ question.pesan }}</h5>
        <div class="row float-right">
            {% if user.profile.role == "Admin" or user.profile.role == "Moderator" %}
                <form action="{% url 'faq:update_faq' %}" method="POST">
                    {% csrf_token %}
                    <input name="id_question" class="card-title" value="{{ question.id }}" hidden>
                    <button class="btn btn-primary column ml-3">Ubah</button>
                </form>
                <button id="{{ forloop.counter }}" class="btn btn-danger column btn-del ml-3" value="{{ question.id }}">Hapus</button>
            {% elif user.profile.role == "User"  %}
            {% endif %}
        </div>
        </div>
    </div>
    {% endfor %}
    <br>
    {% if user.profile.role == "Admin" or user.profile.role == "Moderator" %}
        <form action="{% url 'faq:create_faq' %}">
            <button class="btn btn-primary" type="submit">Ajukan Pertanyaan</button>
        </form>
    {% elif user.profile.role == "User"  %}
    {% endif %}
</section>

<script>
    $(document).ready(function() {
        $(".btn-del").click(function() {
            var id = $(this).val()
            console.log(id)
            if (confirm("Yakin ingin menghapus pertanyaan?")) {
                $.ajax({
                    url: "{% url 'faq:delete_faq' %}",
                    type: "GET",
                    data: {
                        'id' : id,
                    },
                    success: function(response){
                        window.location.href = "/faq/";
                    }
                })
            }
        })
    })
</script>
{% endblock content %}

faq/templates/faq/update-faq.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1 class="text-center">Form Mengubah Pertanyaan</h1>
<div class="container">
    <form method="POST" action="/faq/update2/">
        {% csrf_token %}
        <label for="id_user">ID Pertanyaan:</label><a>{{ id_question }}</a>
        <br>
        <label for="id_pesan">Pertanyaan baru:</label>
        <input name="id_question" class="card-title" value="{{ id_question }}" hidden>
        <textarea id="text-question" name="question" cols="40" rows="10" placeholder="Pertanyaan Anda" class="align-items-center justify-content-center form-control" required></textarea>
        <div class="justify-content-center align-items-center mt-5">
            <button class="btn text-light btn-primary p-1" type="submit">Ubah</button>
        </div>
    </form>
    <button id="btn-batal" class="btn text-light btn-danger p-1 mt-3" type="submit">Batal</button>
</div>

<script>
    $(document).ready(function() {
        $("#btn-batal").click(function(event) {
            $("#text-question").prop('required',false);
            $.ajax({
                url: "{% url 'faq:home' %}",
                type: "GET",
                success: function(response){
                    window.location.href = "/faq/";
                }
            })
        })
    })
</script>
{% endblock content %}