ecwa/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('jurnal/', include('jurnal.urls')),
    path('accounts/', include('accounts.urls')),
    path('comment/', include('comment.urls')),
    path('forum/', include('forum.urls')),
    path('faq/', include('faq.urls')),
    path('error/', include('error.urls')),
]

faq/urls.py
from django.urls import path

from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.home, name='home'),
    path('update2/', views.update_faq_2, name='update_faq_2'),
    path('update/', views.update_faq, name='update_faq'),
    path('create/', views.create_faq, name='create_faq'),
    path('delete/', views.delete_faq, name='delete_faq'),
]

jurnal/urls.py
from django.urls import path

from . import views

app_name = 'jurnal'

urlpatterns = [
    path('', views.jurnal_front, name='jurnal_front'),
    path('add-record/', views.add_record, name='add_record'),
    path('update-record/', views.update_record, name='update_record'),
    path('delete-record/<int:id>/', views.delete_record, name='delete_record'),
    path('drop-record/', views.drop_record, name='drop_record'),
]

jurnal/models.py
from django.db import models

# Create your models here.

class Journal(models.Model):
    usernamezz = models.CharField(max_length=90)
    totals = models.IntegerField(default=0)
    recordtotals = models.IntegerField(default=0)

    def __str__(self):
        return self.usernamezz

class Record(models.Model):
    recordid = models.IntegerField(default=None)
    typezz = models.CharField(max_length=1)
    values = models.IntegerField(default=0)
    journal = models.ForeignKey(Journal, on_delete=models.CASCADE)

    def __str__(self):
        return self.typezz
    
    def value(self):
        return self.values

jurnal/views.py
from django.core.checks import messages
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout as django_logout
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json
from django.contrib.auth.models import User
from .models import Record, Journal
from django.contrib.auth.decorators import login_required

@login_required(login_url="/account/login")
def jurnal_front(request):
    username = request.user.username
    print(username)
    journal = Journal.objects.get(usernamezz = username)
    context = {
        "recordiams" : Record.objects.filter(journal__pk = journal.id),
        "uzername" : username,
        "sumazi" : journal.totals
    }
    # Record.objects.filter(journal=journal)
    return render(request, 'jurnal/jurnalfront.html', context)

@login_required(login_url="/account/login")
def add_record(request):
    if request.method == 'POST':
        jumlah = (int)(request.POST["jumlah"])
        if (int)(jumlah) < 0:
            jumlah = -1 * jumlah
        tipe = request.POST["tipe"]
        journalz = request.user.username
        journale = Journal.objects.get(usernamezz = journalz)
        idz = journale.recordtotals + 1
        journale.recordtotals += 1
        if tipe == "C":
            journale.totals -= (int)(jumlah)
        else:
            journale.totals += (int)(jumlah)
        journale.save()
        new_record = Record.objects.create(recordid = idz, typezz = tipe, values = jumlah, journal = journale)
        new_record.save()
        return redirect('jurnal:jurnal_front')
    return render(request, 'jurnal/formAdd.html')

@login_required(login_url="/account/login")
def update_record(request):
    if request.method == 'POST':
        journalz = request.user.username
        journale = Journal.objects.get(usernamezz = journalz)
        recordo = Record.objects.get(recordid = request.POST['idz'], journal = journale)
        temp = 0
        jumlah = (int)(request.POST["jumlah"])
        if (int)(jumlah) < 0:
            jumlah = -1 * jumlah
        if recordo.typezz == "C":
            if request.POST['tipe'] == "C":
                temp = -1 * ((int)(jumlah) - recordo.values)
            else:
                temp = (int)(jumlah) + recordo.values
        else:
            if request.POST['tipe'] == "C":
                temp = -1 * ((int)(jumlah) + recordo.values)
            else:
                temp = (int)(jumlah) - recordo.values
        journale.totals += temp
        recordo.typezz = request.POST.get('tipe', False)
        recordo.values = request.POST.get('jumlah', False)
        recordo.save()
        journale.save()
        return redirect('jurnal:jurnal_front')
    return render(request, 'jurnal/formUpdate.html')


@login_required(login_url="/account/login")
def delete_record(request, id):
    if request.method == 'POST':
        print(id)
        journalz = request.user.username
        journale = Journal.objects.get(usernamezz = journalz)
        recorde = Record.objects.get(recordid = id, journal = journale)
        val = recorde.values
        print(val)
        if recorde.typezz == "C":
            journale.totals += val
        else:
            journale.totals -= val
        journale.recordtotals -= 1
        journale.save()
        recorde.delete()
    return redirect('jurnal:jurnal_front')


@login_required(login_url="/account/login")
def drop_record(request):
    if request.method == 'POST':
        username = request.user.username
        print(username)
        journal = Journal.objects.get(usernamezz = username)
        records = Record.objects.filter(journal__pk = journal.id)
        records.delete()
        journal.totals = 0
        journal.recordtotals = 0
        journal.save()
        return redirect('jurnal:jurnal_front')
    return render(request, 'jurnal/formDrop.html')

jurnal/templates/jurnal/formAdd.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">Add Record</h3>

    <form method="POST" action="{% url 'jurnal:add_record' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="pb-1">Sum</div>
        <div class="form-group">
          <input type="number" name="jumlah" value="{{request.POST.jumlah}}" class="form-width form-control" placeholder="Jumlah" required>
        </div>
        <div class="pb-1">Type</div>
        <select id="tipe" name="tipe">
          <option value="C">Credit</option>
          <option value="D">Debit</option>
        </select>
    

        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Add</button>
            <a href="{% url 'jurnal:jurnal_front' %}">
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

jurnal/templates/jurnal/formDrop.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">Are you sure?</h3>

    <form method="POST" action="{% url 'jurnal:drop_record' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Drop</button>
            <a href="{% url 'jurnal:jurnal_front' %}">
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

</div>

{% endblock %}

jurnal/templates/jurnal/formUpdate.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="p-5 d-flex flex-column justify-content-center align-items-center">
    <h3 class="mb-3 text-center">Update Record</h3>

    <form method="POST" action="{% url 'jurnal:update_record' %}" class="d-flex flex-column align-items-center">
        {% csrf_token %}
        <div class="pb-1">Record ID</div>
        <div class="form-group">
          <input type="number" name="idz" value="{{request.POST.idz}}" class="form-width form-control" placeholder="ID" required>
        </div>
        <div class="pb-1">Sum</div>
        <div class="form-group">
          <input type="number" name="jumlah" value="{{request.POST.jumlah}}" class="form-width form-control" placeholder="Jumlah" required>
        </div>
        <div class="pb-1">Type</div>
        <select id="tipe" name="tipe" required >
          <option value="C">Credit</option>
          <option value="D">Debit</option>
        </select>
    

        <div class="d-flex w-100 justify-content-around mb-5">
            <button type="submit" class="btn btn-primary">Update</button>
            <a href="{% url 'jurnal:jurnal_front' %}">
              <div class="btn btn-danger">Cancel</div>
            </a>
        </div>
    </form>

    
</div>

{% endblock %}

jurnal/templates/jurnal/jurnalfront.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="jumbotron rounded-0 bg-4 bg-light">
    <h1 class="display-4 text-dark">Economy Journal</h1>
    <div class="d-flex flex-row justify-content-between">
      <p class="lead text-dark">View {{uzername}}'s Journal</p>
      <div class="d-flex flex-row">
        <a role="button" href="{% url 'jurnal:add_record' %}" class="btn btn-primary mr-2">Add Record</a>
        <a role="button" href="{% url 'jurnal:update_record' %}" class="btn btn-primary mr-2">Update Record</a>
        <a role="button" href="{% url 'jurnal:drop_record' %}" class="btn btn-primary">Drop Record</a>
      </div>
    </div>
    <hr class="my-4">
    
    <section>
      <br>
      <div class="Daftar-Item-Table w-75 border-dark m-3">
        <table class="table table-hover table-bordered" id="daftar-item-table">
                <thead>
                  <tr class="table-light" id="table-header">
                    <th>ID</th>
                    <th>Sum</th>
                    <th>Type</th>
                    <th>Delete</th>
                  </tr>
                </thead>
                <tbody class="item-table">
                  {% for recordo in recordiams %}
                  <tr class="table-light">
                    <td>{{ recordo.recordid }}</td>
                    <td>{{ recordo.values }}</td>
                    <td>{{ recordo.typezz }}</td>
                    <td>
                      <form action="{% url 'jurnal:delete_record' recordo.recordid %}" method="POST" class="mr-auto">
                        {% csrf_token %}
                        <button class="btn btn-danger mr-auto" type="input>">
                            Delete
                        </button>
                      </form>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>

        </table>
        <table class="table table-hover bg-primary mb-3 mx-auto" id="daftar-item-table">
          
          
          <thead>
            <tr class="table-light bg-primary mb-3 mx-center" id="table-header">
              <th>Detail : </th>
              <th>{{ sumazi }}</th>
            </tr>
          </thead>

        </table>
      </div> 
    </section>
  </hr>
</div>


  
{% endblock %}